module NFARegexConvTests where

import FA
import Generators
import NFADFAConv
import NFARegexConv
import RegExp
import Test.HUnit
import Test.QuickCheck

prop_roundTripR :: RegExp -> Property
prop_roundTripR r = toRegExp (toNFA r) %==% r

-- not necessarilly equal, generate the same language

prop_roundTripN :: Ord a => NFA a -> Bool
prop_roundTripN nfa =
  let nfa' = toNFA (toRegExp nfa)
   in equivalentDFA (toDFA nfa) (toDFA nfa')

-- not necessarilly equal, accept the same language

-- if you convert a regexp to a nfa, then a string generated by the regexp should be accepted by the nfa
prop_acceptRegExp :: RegExp -> Bool
prop_acceptRegExp = undefined
